### ISSUE TITLE
Open dialog with tail on hover and remain open for interactive elements

### ISSUE THREAD

**Issue by mth-ux-ps** [pluralsight/classic-design-system#1995]
### Desired behavior

Flow would like to use an element, like an info icon, and on hover show something that looks like a tooltip/popover to the end user, so an area with content and a tail pointed at the element (info icon). We want the behavior to be as follows:

1. Hover element (or on focus for accessibility)
2. Be able to move mouse to the popover without it closing
3. Interact within it and it wouldn't close
4. Have option to close popover on click outside, scroll outside, or on hover outside of (tooltip+initial target area)

Within the popover, we want to have interactive elements. 

- Some designs include links to help docs. https://www.figma.com/file/maQpQ6lYgFBUP15tgu7Zgx/Hover-Tooltips-and-Menus?node-id=1612%3A12606 
- Some designs include buttons that link to other pages within the app. https://www.figma.com/file/maQpQ6lYgFBUP15tgu7Zgx/Hover-Tooltips-and-Menus?node-id=1612%3A12607
- Some designs include a mini-carousel to scroll through a few images. https://www.figma.com/file/FD1QQUZWLmMeeVo2ksIjPH/Coaching-1-1-Experiences?node-id=1531%3A23323

We want to make sure these are accessible if someone is using a screen reader to do this, so the element can be activated on hover and on focus. Edward had some good ideas on how to do this.

We want to use and reuse this across the site, plug and play, as much as possible since we want to start implementing these in multiple places.

### Today's behavior

Problems/friction you encounter.

### The Value Add

Why this should be added/changed in the Design System. Where we could use it.

### The Tradeoffs

What we give up or de-optimize to get it. The costs.

**Comment by alexzywiak** [comment]
Let me know if you need any flow specific dev input on this!

**Comment by EdwardIrby** [comment]
@alexzywiak So turns out dialog will not work for what you want because of how it was coded to use FocusManager. I'm out the rest of today and tomorrow. Here is a very basic solution using Tooltip. https://codesandbox.io/s/blissful-lumiere-isvlr?file=/src/example.tsx

However positioning is rough here. I'd honestly recommend combing the example here using the JS examples from Position docs: https://design-system.pluralsight.com/components/position/#javascript-example

For reason I haven't track down yet the JSX position component is iffy with this implementation.

I can come back to this on Thursday.

**Comment by caseybaggz** [comment]
No longer adding features to this project. Closing.
